USE master;
GO

ALTER DATABASE VSHOES1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE VSHOES1 FROM DISK = 'D:\giayvshoes-main 123\vshoes.bak' 
WITH REPLACE, 
MOVE 'VSHOES' TO 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\VSHOES1.mdf', 
MOVE 'VSHOES_log' TO 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\VSHOES1_log.ldf';
GO

ALTER DATABASE VSHOES1 SET MULTI_USER;
GO
